# Generated by Django 3.2.8 on 2021-10-12 22:16

from django.db import migrations

from random import randint
from faker import Faker

from engine.models import Subscriber, SubscriberSMS, Client, User


def generate_fake_data(apps, schema_editor):
    fake = Faker("pl_PL")

    for x in range(randint(10, 50)):
        Subscriber.objects.create(email=fake.email(), gdpr_consent=fake.pybool())

    for x in range(randint(10, 40)):
        SubscriberSMS.objects.create(phone=fake.phone_number(), gdpr_consent=fake.pybool())


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [migrations.RunPython(generate_fake_data)]
